;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GameplayCue.Burn",DevComment="Burn 이펙트")
GameplayTagList=(Tag="My.Cooldown.Fireball",DevComment="Fireball 쿨타임")
GameplayTagList=(Tag="My.Data.Damage",DevComment="즉시 피해 SetByCaller")
GameplayTagList=(Tag="My.State.Debuff.Burn",DevComment="Burn 상태 확인용")

